version: "3"
services:
  db:
    image: "mongo:latest"
    container_name: "mongo-db-database"
    environment:
      - MONGO_INITDB_DATABASE=mongo-test-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./data/mongo-db-volume:/data/db
    restart: always
  api:
    build: ./api
    command: npm run start
    ports:
      - "5000:5000"
    depends_on:
      - db
  client:
    build: ./client
    command: yarn serve -s build
    ports:
      - "3000:3000"
    depends_on:
      - api